spring:
  application:
    name: eureka-discovery
---
spring:
  profiles: eureka1

server:
  port: 8761

eureka:
  instance: 
    hostname: eureka1 
  client:
    serviceUrl:
       defaultZone: http://eureka2:8762/eureka/
    
---
spring:
  profiles: eureka2

server:
  port: 8762

eureka:
  instance: 
    hostname: eureka2  
  client:
    serviceUrl:
       defaultZone: http://eureka1:8761/eureka/

---
spring:
  profiles: ecs1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka.sasubmit.cc
  client:
    serviceUrl:
       defaultZone: http://eureka2.sasubmit.cc:8761/eureka/

---
spring:
  profiles: ecs2

server:
  port: 8761

eureka:
  instance:
    hostname: eureka2.sasubmit.cc
  client:
    serviceUrl:
       defaultZone: http://eureka.sasubmit.cc:8761/eureka/
