spring:
  application: 
    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:/home/ec2-user/submitdemo/config-repo
 
server:
  port: 7001

#spring.cloud.config.server.git.searchPaths

spring.cloud.config.server.native.searchLocations: classpath:/config-repo
#spring.profiles.active: native

logging:
  level:
     springboot: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soldierxue/spring-ecs-config
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
    enabled: true 
    
#       https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/cconfig
