spring:
  application: 
    name: config-server
 
server:
  port: 7001

#spring.cloud.config.server.git.searchPaths

spring.cloud.config.server.native.searchLocations: classpath:/config-repo
spring.profiles.active: native

logging:
  level:
     springboot: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false


#       https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/cconfig